'use strict';
let token='',current=null,cloud={enabled:false,scopes:[]};
const $=id=>document.getElementById(id);
const states={verified:'Цитаты проверены; смысл не проверен',no_context:'Недостаточный контекст',model_refusal:'Модель сообщает нехватку фактов',unverified:'Непроверенный ответ',error:'Техническая ошибка',not_authorized:'Генерация не разрешена',interrupted:'Операция прервана',unknown:'Исход платного вызова неизвестен',searching:'Поиск выполняется',generating:'Генерация выполняется'};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Mentor-Token':token},body:JSON.stringify(data)}:{});const v=await r.json();if(!r.ok)throw Error(v.error||'Ошибка сервера');return v;}
function details(parent,title){const d=node('details');d.append(node('summary',title));parent.append(d);return d;}
function highlighted(parent,text,quotes){let pos=0;const ranges=[];for(const q of quotes){let i=text.indexOf(q);if(i>=0)ranges.push([i,i+q.length]);}ranges.sort((a,b)=>a[0]-b[0]);for(const [start,end] of ranges){if(start<pos)continue;parent.append(document.createTextNode(text.slice(pos,start)));parent.append(node('mark',text.slice(start,end)));pos=end;}parent.append(document.createTextNode(text.slice(pos)));}
function render(item,saved=false){current=item;const out=$('result');out.replaceChildren(node('h2',saved?'Сохранённый результат':'Результат'),node('p',item.question),node('p',states[item.status]||item.status,'status'));if(item.historical)out.append(node('p','Исторический Day24: '+JSON.stringify(item.historical_assessment||'оценка не указана'),'muted'));if(item.reason)out.append(node('p',item.reason));if(item.error)out.append(node('p',item.error,'error'));if(item.save_error)out.append(node('p',item.save_error,'error'));if(item.ledger_save_error)out.append(node('p',item.ledger_save_error,'error'));if(item.answer)out.append(node('p',item.answer.answer));out.append(node('p','Стоимость: '+(item.cost===null||item.cost===undefined?'неизвестна':'$'+item.cost),'muted'));
 const trace=item.search?.trace;if(trace?.temporal?.enabled)out.append(node('p',trace.temporal.error||trace.temporal.interpretation,'period'));const quoted=item.answer?.quotes||[];const selected=trace?.selected||[];const transmitted=item.generation?.transmitted_chunk_ids||[];if(selected.length){const list=details(out,'Выбранные источники · '+selected.length+' / передано модели · '+transmitted.length);for(const c of selected){const source=details(list,(c.source==='assignment'?'Условие':['chat','discussion'].includes(c.source)?'Обсуждение':'Заметка')+' · '+(c.title||c.document_id)+' · '+c.chunk_id);const p=node('div',undefined,'source');highlighted(p,c.text,quoted.filter(q=>q.chunk_id===c.chunk_id).map(q=>q.text));source.append(node('p',c.temporal_restricted?'Полный исходный чанк; поиск и передача ограничены указанными датами.':'Полный исходный чанк','muted'));source.append(p);if(c.message_parts?.length){const attribution=details(source,'Сообщения: авторы, даты и текст');for(const part of c.message_parts){const message=details(attribution,(part.author||'Автор не подтверждён')+' · '+(part.date||'Дата неизвестна')+' · ID '+(part.message_id??part.member_id??'не указан'));const text=node('div',undefined,'source');highlighted(text,part.text,quoted.filter(q=>q.chunk_id===c.chunk_id).map(q=>q.text));message.append(text);}}source.append(node('p',quoted.some(q=>q.chunk_id===c.chunk_id)?'Процитирован':transmitted.includes(c.chunk_id)?'Передан модели, не процитирован':item.generation?.attempted_chunk_ids?.includes(c.chunk_id)?'Передача модели не подтверждена: исход запроса неизвестен':'Выбран поиском; генератору не передавался','muted'));}}
 const diag=details(out,'Диагностика поиска и ответа');if(trace){diag.append(node('p','Найдено кандидатов: '+(trace.candidates?.length||0)+' · выбрано: '+selected.length+' · подтверждена передача: '+transmitted.length,'muted'));diag.append(node('p','Векторное сходство — cosine; итоговый балл — mixed. Это не вероятность правильного ответа.','muted'));const wrapper=node('div',undefined,'table-wrap');const table=node('table');const head=node('tr');for(const text of ['Источник','Cosine','Mixed','Решение'])head.append(node('th',text));const thead=node('thead');thead.append(head);table.append(thead);const tbody=node('tbody');const removed=new Map((trace.removed||[]).map(c=>[c.chunk_id,c.removal_reason]));for(const c of trace.candidates||[]){const row=node('tr');const title=(c.title||c.document_id)+' · '+c.source;for(const value of [title,typeof c.cosine==='number'?c.cosine.toFixed(3):'—',typeof c.mixed_score==='number'?c.mixed_score.toFixed(3):'—',selected.some(s=>s.chunk_id===c.chunk_id)?'Выбран · '+(c.exact_reason?'точное условие':'по баллу'):'Исключён · '+(removed.get(c.chunk_id)||'не выбран')])row.append(node('td',value));tbody.append(row);}table.append(tbody);wrapper.append(table);diag.append(wrapper);}const raw=details(diag,'Полная трасса / исходный ответ');raw.append(node('pre',JSON.stringify({scope:item.scope,authorization:item.authorization,generation:item.generation,search:item.search,validation:item.validation,raw_answer:item.raw_answer,raw_response:item.raw_response,timings:item.timings,cost:item.cost},null,2)));
 const feedback=details(out,'Обратная связь');const form=node('form',undefined,'feedback');for(const label of ['не тот источник','неверный вывод','неполный ответ']){const l=node('label');const check=node('input');check.type='checkbox';check.value=label;check.checked=item.feedback?.marks?.includes(label)||false;l.append(check,document.createTextNode(label));form.append(l);}const comment=node('textarea');comment.placeholder='Комментарий';comment.maxLength=4000;comment.value=item.feedback?.comment||'';form.append(comment);const button=node('button','Сохранить отметку');form.append(button);const status=node('p',undefined,'muted');form.append(status);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{current=await api('/api/feedback',{id:item.id,marks:[...form.querySelectorAll('input:checked')].map(n=>n.value),comment:comment.value});status.textContent='Отметка сохранена';}catch(err){status.textContent=err.message;}finally{button.disabled=false;}};feedback.append(form);}
async function refresh(){const state=await api('/api/state');token=state.token;if(state.public_only){$('scope').querySelector('option[value=all]')?.remove();$('scope').value='public';}cloud=state.cloud;$('policy').textContent=cloud.text;updateMode();$('history').replaceChildren();for(const item of state.history){const b=node('button',item.question,'history-button');b.onclick=async()=>{try{render(await api('/api/result/'+encodeURIComponent(item.id)),true);}catch(e){$('progress').textContent=e.message;}};$('history').append(b);}}
function updateMode(){const active=cloud.enabled&&cloud.scopes.includes($('scope').value);$('send').textContent=active?'Найти и ответить →':'Найти источники →';}
$('scope').onchange=updateMode;
$('ask').onsubmit=async e=>{e.preventDefault();const button=$('send');if(button.disabled)return;button.disabled=true;$('progress').textContent='Поиск по индексу… Закрытие страницы не повторяет запрос.';const ident=crypto.randomUUID();try{const item=await api('/api/ask',{id:ident,question:$('question').value,scope:$('scope').value});render(item);$('progress').textContent=item.saved?'Результат сохранён':'Ошибка сохранения';await refresh();}catch(err){$('progress').textContent=err.message+' · Проверь историю; автоматического повтора нет.';}finally{button.disabled=false;}};
for(const example of document.querySelectorAll('.example-question'))example.onclick=()=>{$('question').value=example.textContent;$('question').focus();};
refresh().catch(e=>$('progress').textContent=e.message);
